### ISSUE TITLE
Installing linter-rubocop causes atom-beautify to stop working

### ISSUE THREAD

**Issue by ryanl-ee** [AtomLinter/linter-rubocop#115]
Hi all! Not sure exactly what the issue is, but I've been able to reproduce this issue by completely uninstalling Atom, deleting my `~/.atom` folder, installing `atom-beautify`, then installing `linter` and `linter-rubocop`. As soon as I install `linter-rubocop`, introduce a Rubocop error, and run atom-beautify, I get this stacktrace:

```
Error: Could not find 'C:\opscode\chefdk\bin\rubocop.BAT'. The program may not be installed.
    at Rubocop.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/RyanLee/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:178:14)
    at file:///C:/Users/RyanLee/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:274:25
    at tryCatcher (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (C:\Users\RyanLee\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:392:9)
```

My problem is with `atom-beautify`, but since it works up until I install `linter-rubocop`, I thought I'd check here first :)

Windows 10
Rubocop from ChefDK 0.12.0
Atom 1.7.0
atom-beautify 0.29.2
linter 1.11.4
linter-rubocop 0.4.7

**Comment by Arcanemagus** [comment]
That is just... bizarre. `atom-beautify` isn't using the same library to run `rubocop` and nothing else is shared so I really have no idea how this could be happening :confused:.

**Comment by karensg** [comment]
Just had the same. You can add the path to robocop.bat in beautify setting in Atom.
Not sure why this happened exactly, but this solved it for me.
![capture](https://cloud.githubusercontent.com/assets/359682/14572896/cc9c2f94-0351-11e6-93a4-738a56233a1f.PNG)
