### ISSUE TITLE
v0.5.0 broke chruby compatibility when lunching from CLI

### ISSUE THREAD

**Issue by pecigonzalo** [AtomLinter/linter-rubocop#168]
On version 0.4.7 lunching Atom from the CLI allowed it to use the CLI path/env variables.
These seems to be broken on 0.5.0

**Comment by Arcanemagus** [comment]
@steelbrain Looks like this is a `consistent-env` issue, you would know better than I how to debug this.

**Comment by steelbrain** [comment]
@pecigonzalo Can you tell us your OS, shell and the env variables in question?

**Comment by pecigonzalo** [comment]
Archlinux, ZSH (with zplug).
The envs are `GEM_HOME` and `GEM_PATH`, if it doesnt import them, it breaks rubocop from chruby. If you need the output of this or `gem env` i can provide tomorrow.

I tried looking at the code, but tbh i dont know much about atom plug deployment or how are you importing the envs, so i couldnt figure out what is different.

**Comment by steelbrain** [comment]
Can you do `echo $GEM_HOME` from terminal and show output of `process.env.GEN_HOME` from Atom dev tools window?

**Comment by pecigonzalo** [comment]
Unfortunately my laptop if out of juice at the moment and i dont have the adapter with me (the device i initially tested with).
I can provide that output tomorrow.

**Comment by goronfreeman** [comment]
I wanted to chime in on this issue as well. I'm seeing the same thing. macOS 10.12 with ZSH (oh-my-zsh).

```shell
echo $GEM_HOME
```

**Comment by pecigonzalo** [comment]
As agreed:
```
➔ echo $GEM_HOME
/home/gonzalop/.gem/ruby/2.2.5
```
Atom console
```
> process.env.GEN_HOME
<- undefined
```

And the error:
```
Error: /home/gonzalop/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'rubocop' (>= 0) among 9 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/.gem/ruby/2.2.0:/home/gonzalop/.rubies/ruby-2.2.5/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /home/gonzalop/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/gonzalop/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/gonzalop/.gem/ruby/2.2.5/bin/rubocop:22:in `<main>'
    at /home/gonzalop/.atom/packages/linter-rubocop/lib/index.coffee:57:15
```

**Comment by steelbrain** [comment]
@goronfreeman Yes Mac apps have that issue. Therefore we fix it with `consistent-env` when spawning. Can you see if the result is in `require('/Users/[name]/.atom/packages/linter-rubocop/node_modules/consistent-env')().GEM_HOME`?

@pecigonzalo Thanks that was very helpful, can you show the output of `require('/Users/[name]/.atom/packages/linter-rubocop/node_modules/consistent-env')()` (make sure to remove anything sensitive like s3 keys and stuff, never post them on public forums :)

**Comment by pecigonzalo** [comment]
```
{USER: "gonzalop", PATH: "/home/gonzalop/.gem/ruby/2.2.5/bin:/home/gonzalop/…ndor_perl:/usr/bin/core_perl:/bin:/usr/sbin:/sbin", OLDPWD: "/home/gonzalop/Workspace/Zenmate/chef", PWD: "/home/gonzalop/Workspace/Zenmate/chef"}
```

**Comment by goronfreeman** [comment]
@steelbrain When launching from the GUI, that command outputs `undefined`. Let me know if this isn't the thread to discuss this, but I appreciate the help. Thanks!

**Comment by 5t111111** [comment]
I use zplug too and have a similar issue with v0.5.0, when it runs linter-rubocop, I encounter the following error:

```
Error: couldn't find HOME environment -- expanding `~'
```

- Downgrading linter-rubocop to v0.4.7
- Removing zplug from my `.zshrc`

Either of the above two fixes the problem.

OS: OS X 10.11.6
Shell: Zsh

**Comment by 5t111111** [comment]
After some further investigation, I've found that the problem in the above comment is occurs only when I use a specific plugin (in my case, that is [emoji-cli](https://github.com/b4b4r07/emoji-cli)) via zplug.

Although I still don't know why the problem occurs only after upgrading linter-rubocop v0.5.0, either I'm not sure if other plugins rather than emoji-cli also cause errors, maybe I should investigate emoji-cli for the moment.

**Comment by joshRpowell** [comment]
@5t111111 I can confirm that this issue still exists with `emoji-cli` via zplug.  were you able to make any progress on this?
