### ISSUE TITLE
Error: spawn rubocop ENOENT

### ISSUE THREAD

**Issue by jamesgecko** [AtomLinter/linter-rubocop#172]
After updating to Atom 1.11.2, I've started getting this error notification:
```
Error: spawn rubocop ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
Do you have `rubocop` installed on your system? Does `which rubocop` show anything?

**Comment by jamesgecko** [comment]
`which rubocop` shows that the binary is in `/Users/james/.rbenv/shims/rubocop`. Setting that absolute path in the plugin settings resolves the issue. No idea why this suddenly broken.
