### ISSUE TITLE
Failed to activate the linter-rubocop package

### ISSUE THREAD

**Issue by AlexWayfer** [AtomLinter/linter-rubocop#203]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: linux 4.10.4-1-ARCH
**Thrown From**: [linter-rubocop](https://github.com/AtomLinter/linter-rubocop) package 1.1.1

### Stack Trace

Failed to activate the linter-rubocop package

```
At Cannot find module 'escape-html'

Error: Cannot find module 'escape-html'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-rubocop/src/index.js:5:24)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:922:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/app.asar/src/package-manager.js:581:36)
    at /app.asar/src/package-manager.js:512:17
```

### Commands

```
```

### Non-Core Packages

```
.bin undefined 
advanced-open-file 0.16.6 
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-ui undefined 
atom-smart-tabs 0.1.0 
atom-typescript undefined 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.5 
autocomplete-ruby 0.2.6 
autoupdate-packages 1.3.1 
busy-signal 1.3.0 
color-picker 2.2.5 
crystal 0.2.0 
editorconfig 2.2.2 
genesis-ui 0.5.0 
git-time-machine 1.5.6 
goto-definition 1.2.1 
hex 0.6.2 
highlight-selected 0.12.0 
intentions 1.1.2 
language-babel 2.57.0 
language-crystal-actual 0.33.0 
language-fish-shell 1.0.5 
language-haml 0.24.1 
language-vue 0.21.2 
linter 2.1.1 
linter-erb 1.0.4 
linter-eslint 8.1.4 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-markdown 3.1.0 
linter-reek 2.2.1 
linter-rubocop 1.1.1 
linter-ruby 1.2.5 
linter-stylelint 3.9.0 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
monocolor-blue-syntax 1.0.0 
monokai 0.22.0 
nucleus-dark-ui 0.11.0 
remember-file-positions 0.2.2 
revert-buffer 0.5.0 
ruby-block 0.3.6 
ruby-define-method 0.2.2 
seti-icons 1.4.3 
seti-ui 1.7.0 
single-click-open 0.2.2 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.2.1 
symbols-tree-view 0.13.2 
sync-settings 0.8.1 
synced-sidebar 0.4.3 
tab-control 0.6.9 
tabs-to-spaces 1.0.3 
tasks 2.6.6 
term3 0.22.1 
todo-show undefined 
toggle-quotes 1.0.1 
tree-view-open-files 0.3.0 
yard 0.3.1 
zentabs 0.8.8 
```

**Comment by AlexWayfer** [comment]
```
$ apm uninstall linter-rubocop
$ apm install linter-rubocop
```

Resolved.

**Comment by sammiearchie77** [comment]
Please I have a similar problem but mine is saying Error: Can not find module './linters/rubocup
I'm using Elementory OS

what's the solution?

**Comment by AlexWayfer** [comment]
> Please I have a similar problem but mine is saying Error: Can not find module './linters/rubocup
> I'm using Elementory OS
> 
> what's the solution?

Did you try commands from my comment above?

**Comment by sammiearchie77** [comment]
yes I did. The command didn't work on my machine. However I have fixed it with this command npm install linter-bundle --save-dev
