### ISSUE TITLE
Uncaught Error: Column start (9) greater than line length (6) for line 28

### ISSUE THREAD

**Issue by bronson** [AtomLinter/linter-rubocop#238]
[Enter steps to reproduce:]

1. I don't know how to reproduce this.  I was editing `webpack.config.js` at the time, no ruby files open that I can see.  Hoping the stack trace will suggest a fix...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [linter-rubocop](https://github.com/AtomLinter/linter-rubocop) package 2.1.1

### Stack Trace

Uncaught Error: Column start (9) greater than line length (6) for line 28

```
At /Users/bronson/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/index.js:181

Error: Column start (9) greater than line length (6) for line 28
    at generateRange (/packages/linter-rubocop/node_modules/atom-linter/lib/index.js:181:11)
    at getRange (/packages/linter-js-standard/lib/utils/linter.js:16:10)
    at /packages/linter-js-standard/lib/utils/linter.js:39:19
    at Array.forEach (native)
    at Object.module.exports (/packages/linter-js-standard/lib/utils/linter.js:29:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:05.2.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -2:02.0 core:backspace (input.hidden-input)
     -1:58.5.0 editor:newline (input.hidden-input)
  7x -1:57.2.0 core:backspace (input.hidden-input)
     -1:55 editor:newline (input.hidden-input)
     -1:53.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -1:53 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -1:52.9.0 vim-mode-plus:move-up (input.hidden-input)
     -1:52.5.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -1:47.9.0 core:backspace (input.hidden-input)
     -1:42.9.0 editor:newline (input.hidden-input)
     -1:37.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -1:37.3.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -1:36.4.0 vim-mode-plus:move-up (input.hidden-input)
  3x -1:36.1.0 vim-mode-plus:move-left (input.hidden-input)
  2x -1:34.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-ide-ui 0.3.1 
atom-ternjs 0.18.3 
autocomplete-ctags 0.4.1 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
color-picker 2.2.5 
cursor-history 0.12.0 
ex-mode 0.18.0 
ex-mode-sort 1.0.0 
file-icons 2.1.11 
highlight-selected 0.13.1 
ide-typescript 0.6.1 
intentions 1.1.5 
language-apache 1.7.0 
language-babel 2.74.1 
language-diff 0.7.0 
language-gradle 0.0.3 
language-haml 0.25.1 
language-javascript-jsx 0.3.7 
language-rust 0.4.12 
language-slim 0.6.0 
language-viml 1.1.4 
linter 2.2.0 
linter-clang 4.1.2 
linter-coffeelint 1.3.1 
linter-eslint 8.2.1 
linter-haml 2.0.2 
linter-js-standard 4.0.0 
linter-js-yaml 1.2.7 
linter-jsonlint 1.3.0 
linter-rubocop 2.1.1 
linter-ruby 1.2.6 
linter-rust 0.8.0 
linter-slim 1.0.0 
linter-stylelint 4.0.2 
linter-tidy 2.3.1 
linter-ui-default 1.6.8 
linter-write-good 0.9.0 
narrow 0.51.0 
oceanic-reef-syntax 0.9.0 
open-this 0.4.0 
package-sync 1.1.0 
paner 1.0.0 
prettier-atom 0.38.0 
racer 0.20.0 
rails-transporter 1.7.1 
rubocop-auto-correct 1.5.1 
ruby-test-switcher 1.2.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
tablr 1.8.3 
tester 1.4.0 
tester-jest 1.1.6 
tester-mocha 1.0.0 
todo-show 2.0.0 
ubik-neon-syntax 1.9.1 
vim-mode-plus 1.4.0 
vim-mode-plus-jasmine-increase-focus 0.3.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
white-cursor 0.7.0 
```

**Comment by Arcanemagus** [comment]
Are you still seeing this? If so, are you able to share a file that shows this?

This error comes up when the provider is giving us a point that doesn't actually exist in the file in question.

**Comment by bronson** [comment]
No idea how to repro.  Happy to close the issue if there's nothing interesting here.

**Comment by Arcanemagus** [comment]
Closing it then, if you ever see this again please save the file in that _exact_ state and create a new issue with it if you are able to share it 😉.
