### ISSUE TITLE
Couldn't find rubocop

### ISSUE THREAD

**Issue by joaovitorkazap** [AtomLinter/linter-rubocop#247]
I'm having the following error:

```
/home/joaovitor/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running RuboCop Error: /home/joaovitor/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'rubocop' (>= 0) among 8 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/joaovitor/Documentos/saudesimples/vendor/bundle/ruby/2.1.0', execute `gem env` for more information
	from /home/joaovitor/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/joaovitor/.rvm/rubies/ruby-2.1.9/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/joaovitor/.rvm/gems/ruby-2.1.9/bin/rubocop:22:in `<main>'
	from /home/joaovitor/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:15:in `eval'
	from /home/joaovitor/.rvm/gems/ruby-2.1.9/bin/ruby_executable_hooks:15:in `<main>'
    at parseFromStd (/home/joaovitor/.atom/packages/linter-rubocop/src/index.js:41:43)
    at Object.<anonymous> (/home/joaovitor/.atom/packages/linter-rubocop/src/index.js:221:27)
    at Generator.next (<anonymous>)
    at step (/home/joaovitor/.atom/packages/linter-rubocop/src/index.js:11:273)
(anonymous) @ /home/joaovitor/.atom/packages/linter/lib/linter-registry.js:159
```

**Comment by Arcanemagus** [comment]
@joaovitorkazap It looks like you have two potential causes here:
* You haven't installed the `rubocop` gem in the first place
* `rvm` is (yet again) messing things up. You either need to close _all_ Atom instances and launch Atom from a terminal where you have `rvm` running in the right environment, or you need to specify the path to a _wrapper_ version of `rubocop` from `rvm`.

**Comment by tpitale** [comment]
I'm getting something similar with linter-rubocop 2.2.3, linter 2.2.0, and Atom 1.24.0.

I'm using `chruby`, so `which rubocop` shows `/Users/<username>/.gem/ruby/2.5.0/bin/rubocop`.

* Starting atom from the CLI. ✅ 
* If I open the dev tools and check `process.env` it shows the correct `GEM_HOME` and `GEM_PATH` and `PATH` include the `/Users/<username>/.gem/ruby/2.5.0/bin` where `rubocop` is located. ✅ 
* Running `rubocop` from CLI works as expected ✅ 
* Tried changing settings for the command to point to the full path `/Users/<username>/.gem/ruby/2.5.0/bin/rubocop`, same errors. ✅ 

Error for me complains that the gem rubocop isn't installed correctly (missing other gems). So, not sure what command or version of rubocop this is trying to run, but it does not appear to be respecting settings or env in some way.

Not sure what to try next @Arcanemagus

**Comment by tpitale** [comment]
Also, this setup was working previously, and only seemed to fail after a recent upgrade to linter-rubocop. Not sure if I can downgrade to an earlier version of linter-rubocop.

**Comment by tpitale** [comment]
I've now tried to uninstall every linter-related package and re-install. Same errors.

**Comment by tpitale** [comment]
Changed the command to `/usr/local/bin/chruby-exec $RUBY_VERSION -- rubocop` but now it can't find `chruby`. `zsh:1: command not found: chruby`, this seems weird given that all the ENV variables are set correctly … how is it not sourcing chruby …

**Comment by tpitale** [comment]
I've resolved my issue by sourcing zshrc into zprofile: https://github.com/moxley/atom-ruby-test/issues/60 and using `/usr/local/bin/chruby-exec 2.5.0 -- rubocop` as the command. This works for now.

**Comment by vzamanillo** [comment]
I am closing this due to inactivity, be free to reopen it if you still experiencing the same problem.
