### ISSUE TITLE
Linter fails when specifying --format in .rubocop

### ISSUE THREAD

**Issue by jamesm6162** [AtomLinter/linter-rubocop#260]
Using Rubocop 0.52.1 Linter fails to run when I use a .rubocop file that looks like this:
```
--format
simple
```
However running the Rubocop CLI supports the arguments just fine.

Other arguments work fine in the .rubocop file, such as: 
```
--display-cop-names
--rails
```

Error displayed in the Developer tools is not very explanatory:
```
[Linter] Error running RuboCop Error: Inspecting 1 file      <home_dir>/.atom/packages/linter/lib/linter-registry.js:159
.

1 file inspected, no offenses detected
{"metadata":{"rubocop_version":"0.52.1","ruby_engine":"ruby","ruby_version":"2.4.0","ruby_patchlevel":"0","ruby_platform":"x86_64-darwin15"},"files":[{"path":"../<path_to_file>","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}
    at parseFromStd (<home_dir>/.atom/packages/linter-rubocop/src/index.js:43:43)
    at Object.<anonymous> (<home_dir>/.atom/packages/linter-rubocop/src/index.js:255:27)
    at Generator.next (<anonymous>)
    at step (<home_dir>/.atom/packages/linter-rubocop/src/index.js:13:273)
```

**Comment by vzamanillo** [comment]
Closed for cleanup. Be free to reopen it if the problem persist.
