### ISSUE TITLE
[Linter] Error running RuboCop TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by RyanMcDonald** [AtomLinter/linter-rubocop#263]
I am using rbenv with Rubocop 0.49.1.

My rubocop.yml inherits from a private gem that we created within our organization to share Rubocop rules across projects. This gem is installed via bundler by specifying the private GitHub repository.

Because of the above, my Rubocop executable needs to be `/Users/ryan/.rbenv/shims/bundle exec rubocop` in order for it to be able to find the private gem when executing Rubocop. However, when I do this, linter-rubocop throws this error:

```
[Linter] Error running RuboCop TypeError: Invalid Version: undefined
    at new SemVer (/Users/ryan/.atom/packages/linter-eslint/node_modules/semver/semver.js:291:11)
    at compare (/Users/ryan/.atom/packages/linter-eslint/node_modules/semver/semver.js:578:10)
    at Function.gte (/Users/ryan/.atom/packages/linter-eslint/node_modules/semver/semver.js:627:10)
    at /Users/ryan/.atom/packages/linter-rubocop/src/index.js:143:14
    at Generator.next (<anonymous>)
    at step (/Users/ryan/.atom/packages/linter-rubocop/src/index.js:13:273)
```

**Comment by chasebolt** [comment]
We are running into this issue as well when using cookstyle from chefdk

```shell
$ cookstyle -v             
Cookstyle 2.1.0              
  * RuboCop 0.49.1 
```

```shell
$ rubocop -v
0.49.1
```

**Comment by ardation** [comment]
+1

**Comment by Averethel** [comment]
+ 1

**Comment by andypike** [comment]
I have a similar issue. My command is `bundle exec rubocop` and up until recently it has worked perfectly. Now I get the same error as the OP. 

After looking into it for a little bit it seems related to this snippet in `index.js`:

```javascript
const determineExecVersion = async (execPath) => {
  const versionString = await helpers.exec(execPath, ['--version'], { ignoreExitCode: true })
  const versionPattern = /^(\d+\.\d+\.\d+)/i
  const match = versionString.match(versionPattern)

  if (match !== null && match[1]) {
    execPathVersions.set(execPath, match[1])
  }
}
```

If you inspect `execPath` it is set to `bundle` (rather than the command `bundle exec rubocop` I was expecting). If you also look at `versionString` it is set to `Bundler version 1.16.0` as it trying to do `bundle --version` rather than `bundle exec rubocop --version`.

I'm not sure of the correct fix here as I don't know much about how Atom works but I hope this helps.

Thanks for everything, I use the package everyday, it's so helpful ❤️

**Comment by sharkeyryan** [comment]
For those running rbenv, you can possibly fix this by pointing your atom linter to use the rbenv shims version.

1. Open your atom config by clicking "Atom" menu and selecting `"Config..."`


2. Find your linter-rubocop command setting by running:

`which rubocop`

3. Update your atom config.cson file with:

```
"linter-rubocop":
  command: "/Users/**<youraccount>**/.rbenv/shims/rubocop"
```

**Comment by briankung** [comment]
Thanks @sharkeyryan, that worked for me. Hopefully #262 will fix it for good.

**Comment by Arcanemagus** [comment]
Oh wow, _every_ other provider is written with the main path to the linter being _just_ that, any additional configurable arguments are stored in a separate configuration. It looks like this provider merged them for some bizarre reason 😮.

I'll look into #262 and likely get that merged, or will put together something that fixes it otherwise if that doesn't handle it. Sorry about this!

On a related note, it seems this project is without an active maintainer that actually uses the provider, so if anyone wanted to step up that would be amazing 😉.

**Comment by maschwenk** [comment]
@Arcanemagus yeah....apologies, I've moved to VSCode. Unfortunately this plugin is much better but I like a lot of other stuff. I'm trying to make the VSCode one better but unfortunately not using Atom as my daily driver.

**Comment by Arcanemagus** [comment]
No worries @maschwenk, that's why this is part of an organization so it can continue on 😉.

**Comment by vzamanillo** [comment]
I am closing this due to inactivity, anyway, the Rubocop version is now obtained directly from the output (#301)
