### ISSUE TITLE
-s/--stdin requires exactly one path error when .rubocop file present

### ISSUE THREAD

**Issue by abraham** [AtomLinter/linter-rubocop#266]
I've got a `.rubocop` file

```
AllCops:
  TargetRubyVersion: 2.5.0

Metrics/LineLength:
  Max: 120
```

And this results in the following error
```
[Linter] Error running RuboCop Error: -s/--stdin requires exactly one path.
/Users/abraham/.rvm/gems/ruby-2.5.0/gems/rubocop-0.53.0/lib/rubocop/options.rb:29:in `parse'
/Users/abraham/.rvm/gems/ruby-2.5.0/gems/rubocop-0.53.0/lib/rubocop/cli.rb:37:in `run'
/Users/abraham/.rvm/gems/ruby-2.5.0/gems/rubocop-0.53.0/bin/rubocop:13:in `block in <top (required)>'
/Users/abraham/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/abraham/.rvm/gems/ruby-2.5.0/gems/rubocop-0.53.0/bin/rubocop:12:in `<top (required)>'
/Users/abraham/.rvm/gems/ruby-2.5.0/bin/rubocop:23:in `load'
/Users/abraham/.rvm/gems/ruby-2.5.0/bin/rubocop:23:in `<main>'
/Users/abraham/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/abraham/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
    at parseFromStd (/Users/abraham/.atom/packages/linter-rubocop/src/index.js:formatted:134)
    at Object.<anonymous> (/Users/abraham/.atom/packages/linter-rubocop/src/index.js:formatted:358)
    at Generator.next (<anonymous>)
    at step (/Users/abraham/.atom/packages/linter-rubocop/src/index.js:formatted:85)
    at process._tickCallback (internal/process/next_tick.js:103)
```

If I delete the contents of the `.rubocop` file the linting works without error.

**Comment by vzamanillo** [comment]
This package pipes the editor content to Rubocop `stdin` internally, looks like Rubocop does not allow the use of `stdin` in combination with an arguments file, alternatively you can put your configuration on a `.rubocop.yml` file.

```
    def parse(command_line_args)
      args = args_from_file.concat(args_from_env).concat(command_line_args)
      define_options.parse!(args)

      @validator.validate_compatibility

      if @options[:stdin]
        # The parser will put the file name given after --stdin into
        # @options[:stdin]. If it did, then the args array should be empty.
        raise OptionArgumentError, E_STDIN_NO_PATH if args.any?

        # We want the STDIN contents in @options[:stdin] and the file name in
        # args to simplify the rest of the processing.
        args = [@options[:stdin]]
        @options[:stdin] = $stdin.binmode.read
      end

      [@options, args]
    end

    private

    def args_from_file
      if File.exist?('.rubocop') && !File.directory?('.rubocop')
        IO.readlines('.rubocop').map(&:strip)
      else
        []
      end
    end
```

**Comment by abraham** [comment]
I've moved to VS Code so this is no longer an issue for me.
