### ISSUE TITLE
Failed to spawn error

### ISSUE THREAD

**Issue by XOmniverse** [AtomLinter/linter-rubocop#272]
I installed Atom using the flatpak on Fedora 28 (very recent, just released today) and I cannot get this package to work. I see the following error in the Developer Console:

```
/home/xomniverse/.var/app/io.atom.Atom/data/packages/linter/lib/linter-registry.js:159 [Linter] Error running RuboCop Error: Failed to spawn command `/usr/local/bin/rubocop`. Make sure `/usr/local/bin/rubocop` is installed and on your PATH
    at /home/xomniverse/.var/app/io.atom.Atom/data/packages/linter-ruby/node_modules/atom-linter/lib/helpers.js:130:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

The executable in question (/usr/local/bin/rubocop) works fine and has 755 permissions:

```ShellSession
[~]$ which rubocop                                                                  
/usr/local/bin/rubocop
[~]$ ls -la /usr/local/bin/rubocop                                                  
-rwxr-xr-x. 1 root root 601 May  1 09:34 /usr/local/bin/rubocop
[~]$ rubocop -v                                                                     
0.55.0
```

I also have the rubocop gem installed, both for root and for my local user:

```ShellSession
[~]$ gem list rubocop                                                               

*** LOCAL GEMS ***

rubocop (0.55.0)
[~]$ sudo gem list rubocop                                                          
[sudo] password for xomniverse: 

*** LOCAL GEMS ***

rubocop (0.55.0)
```

**Comment by vzamanillo** [comment]
Hi @XOmniverse , did you try with the latest linter-rubocop version?

**Comment by vzamanillo** [comment]
Closed for cleanup. Be free to reopen it if the problem persist.
