### ISSUE TITLE
Rubocop linter stopped working

### ISSUE THREAD

**Issue by mrfoto** [AtomLinter/linter-rubocop#63]
My issue is similar to #61 - it used to work but it's broken with recent versions. I use `chruby` and specify the executable path explicitly `/Users/mrfoto/.gem/ruby/2.2.2/bin/rubocop`. But every file I open I get the following error popups and rubocop is not linting:
```
Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in to_specs': Could not find 'rubocop' (>= 0) among 8 total gem(s) (Gem::LoadError) from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:into_spec' from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in gem' from /Users/mrfoto/.gem/ruby/2.2.2/bin/rubocop:22:in
'
```
```
Error: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'rubocop' (>= 0) among 8 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /Users/mrfoto/.gem/ruby/2.2.2/bin/rubocop:22:in `<main>'
  at /Users/mrfoto/.atom/packages/linter-rubocop/index.coffee:42:27
  at FSReqWrap.oncomplete (fs.js:77:15)
```

So it is finding the right rubocop as this happens from line 22 of it but it still accesses some system paths where rubocop (or anything else) is not present.

**Comment by mrfoto** [comment]
Works again in the latest version
