### ISSUE TITLE
Error: -s/--stdin requires exactly one path.

### ISSUE THREAD

**Issue by antoinehebert** [AtomLinter/linter-rubocop#78]
I get the following error after the latest 0.4.4 update.

Thanks!

```
Error: -s/--stdin requires exactly one path.
/Users/ahebert/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/lib/rubocop/options.rb:25:in `parse'
/Users/ahebert/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/lib/rubocop/cli.rb:21:in `run'
/Users/ahebert/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/bin/rubocop:13:in `block in <top (required)>'
/Users/ahebert/.rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/ahebert/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rubocop-0.34.2/bin/rubocop:12:in `<top (required)>'
/Users/ahebert/.rbenv/versions/2.2.2/bin/rubocop:23:in `load'
/Users/ahebert/.rbenv/versions/2.2.2/bin/rubocop:23:in `<main>'
    at /Users/ahebert/.atom/packages/linter-rubocop/index.coffee:30:15
```

**Comment by yarafan** [comment]
Got the same problem. After the latest update executable path to rubocop was wrong. So after fixing settings everything works fine

**Comment by antoinehebert** [comment]
Oh right, after the update the path was now "patth/to/rubocop undefined". Fixed this and now everything is back to normal!

Thanks @yarafan
