### ISSUE TITLE
Make arguments to rubocop configurable

### ISSUE THREAD

**Issue by joerg** [AtomLinter/linter-rubocop#90]
I am working on Windows (don't ask, it is just temporary and they pay very very well) with ChefDk [1] which bundles rubocop 0.32.1. Now configuring the rubocop executable works like a charm, but I get this error:
```
Error: invalid option: --cache C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/lib/rubocop/options.rb:68:in parse' C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:21:inrun' C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/bin/rubocop:13:in block in <top (required)>' C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:294:inrealtime' C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/bin/rubocop:12:in <top (required)>' C:/LocalData/WZHHEJ/Applications/opscode/chefdk/bin/rubocop:23:inload' C:/LocalData/WZHHEJ/Applications/opscode/chefdk/bin/rubocop:23:in `

'
Error: invalid option: --cache
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/lib/rubocop/options.rb:68:in `parse'
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/lib/rubocop/cli.rb:21:in `run'
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/bin/rubocop:13:in `block in <top (required)>'
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rubocop-0.32.1/bin/rubocop:12:in `<top (required)>'
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/bin/rubocop:23:in `load'
C:/LocalData/WZHHEJ/Applications/opscode/chefdk/bin/rubocop:23:in `<main>'
    at file:///C:/Users/WZHHEJ/.atom/packages/linter-rubocop/index.coffee:30:15
    at process._tickCallback (node.js:368:9)
```

The problem is that this version does not have the cache option yet. I think it would be a good idea to make the options passed to rubocop configurable, that we any error like this could be fixed locally by the user.

[1] https://downloads.chef.io/chef-dk/

**Comment by caseywebdev** [comment]
The linter only works with rubocop v0.34.0 or higher because that's when STDIN linting support was introduced. The arguments are already configurable, with the exception of necessary flags like `--cache false` and `--format json`. You can try installing an older version of linter-rubocop and seeing how well that works but I don't really think backporting is going to happen.
